### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by moocan** [Dook1/Discard-Dook#1]
Hello,

Impossible to install extension from [Mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/discard-dook/) even in debugging mode.
No problem with other extensions. Not related to certificate bug.

`There was an error during installation: Extension is invalid`

Kind Regards

**Comment by Dook1** [comment]
browser version number?

**Comment by moocan** [comment]
Hello,

Tested on 61.0.1 (Linux x64) and with last version 67.0

Here what I have logged:
`Error: "Extension is invalid"
loadManifestFromWebManifestresource://gre/modules/addons/XPIInstall.jsm:513:11 Controls.js:85:9
	installAddon/< resource://devtools/client/aboutdebugging/components/addons/Controls.js:85:9
`

Kr,

**Comment by Dook1** [comment]
Just checked. Loaded and running.

**Comment by moocan** [comment]
Hello,

Thank you for your return.
Seems to be working with 67.0 but can't get it to work with 61.x
Will try to restart Firefox.

Kr,

**Comment by moocan** [comment]
Hello,

I'm closing this issue because I do not encountered any trouble with Firefox >= 67.0.

Thank you for your great work, because it is working just very well.
I didn't notice any issue with other add-ons as Tree Style Tabs, Temporary Containers or Tab Session Manager.
I don't use the kill feature, only the discard one but I really love the dashboard (Tab Manager) to see all tabs status, the counter because now I know how many tabs I have and the notification when a tab is discarded. 
As just a suggestion, the name of your add-on in place of the the add-on GUID in the tab's name and an export/import settings would be a great addition.

Thank you for this great add-on.
Regards.
