### ISSUE TITLE
[not an issue] Simple feature request

### ISSUE THREAD

**Issue by EstherMoellman** [Dook1/Discard-Dook#2]
Hi @Dook1 ,

Thank you for your add-on.
Please, if possible, I would like to request you a feature:

I am really interested only in what you call "kill function".
However, the current "restore function" is complicated when the user has lot of tabs, because the current "restore function" forces to restore one or all tabs.

In this context, firstly it will be fantastic to have at Discard-Dook, the possibility to work with GROUPS (not just different windows). Groups are working in same window.
And secondly, also it will be great if Discard-Dook may restore tabs by Groups.

In my opinion, this should be a small addition to current Discard-Dook, because today almost everything already is there, just need to add the possibility to work with Groups, and restore killed tabs by Groups.

This small change may launch Discard-Dook as a formidable new kind of tab manager. I explain:
Normally are two kind of tab manager:
- "Hiding/Discarding" tabs
- Working as session managers, "Bookmarking/Closing" tabs

Sadly, most of the tab manager use Hiding/Discarding, which creates privacy, security and browser performance issues, not to mention also lot of conflicts with other add-ons, and conflicts with the browser itself.
Only a few tab managers use Bookmarking/Closing, and these add-ons are too basic, too raw, primitive, almost useless.

Your Discard-Dook add-on may become a kind of tab manager using "Bookmarking/Closing" tabs. For that, it just need today the capability to work with Groups... that's all!
With this small change allowing to work with Groups and restoring tabs by Groups, voilà, you may have a fantastic new tab manager, different from the other tab manager, because your add-on will be focused on privacy, security, browser performance and minimizing conflicts (with other add-ons/browser itself).

Your "kill function" here is the key.
By saving tabs as bookmarks, and closing them... privacy, security, browser performance is increased, while conflicts are minimized.

I hope you will think about this opportunity., because there is no similar good add-on using Groups and Bookmarking/Closing tabs.

Thank in advance!

**Comment by Dook1** [comment]
> the current "restore function" forces to restore one or all tabs.
>
LMB+Shift or LMB+Ctrl

Do you work for Mozilla?

**Comment by EstherMoellman** [comment]
Nope, I'm not working at Mozilla, I'm a simple user.

And sadly, nope, the "LMB+x" is far away from my request.

But thank you anyway.

**Comment by Dook1** [comment]
This is already in Firefox, called bookmarks.


> Nope, I'm not working at Mozilla, I'm a simple user.

> 

And judging by the text - you working.

**Comment by EstherMoellman** [comment]
"LMB+x" or "bookmarks" are far away from my request, in the negative sense. What you suggest has almost nothing to do with my request.
And if you ask me if I'm a FF' employee, I answer "no", and you still believe I'm a FF' employee, man what can I say you?, perhaps a psychologist can help you : )
Thank you for your useless help.

**Comment by Dook1** [comment]
> "LMB+x" or "bookmarks" are far away from my request

> 
I think you yourself don't know your request.

> perhaps a psychologist can help you
> 
And you - only a psychiatrist. 

 But Mozilla should take a more serious approach to the selection of specialists in the department for work with authors of extensions.
